-- Inserção dos paises no banco
-- Países membros da ONU (193) com códigos ISO 3166-1 alpha-2.

INSERT INTO pais (id, nome, continente, requer_visto) VALUES
    ('AF', 'Afeganistão', 'Ásia', TRUE),
    ('AL', 'Albânia', 'Europa', FALSE),
    ('DZ', 'Argélia', 'África', TRUE),
    ('AD', 'Andorra', 'Europa', FALSE),
    ('AO', 'Angola', 'África', TRUE),
    ('AG', 'Antígua e Barbuda', 'América do Norte', FALSE),
    ('AR', 'Argentina', 'América do Sul', FALSE),
    ('AM', 'Armênia', 'Ásia', FALSE),
    ('AU', 'Austrália', 'Oceania', FALSE),
    ('AT', 'Áustria', 'Europa', FALSE),
    ('AZ', 'Azerbaijão', 'Ásia', FALSE),
    ('BS', 'Bahamas', 'América do Norte', FALSE),
    ('BH', 'Bahrein', 'Ásia', FALSE),
    ('BD', 'Bangladesh', 'Ásia', FALSE),
    ('BB', 'Barbados', 'América do Norte', FALSE),
    ('BY', 'Belarus', 'Europa', FALSE),
    ('BE', 'Bélgica', 'Europa', FALSE),
    ('BZ', 'Belize', 'América do Norte', FALSE),
    ('BJ', 'Benim', 'África', FALSE),
    ('BT', 'Butão', 'Ásia', TRUE),
    ('BO', 'Bolívia', 'América do Sul', FALSE),
    ('BA', 'Bósnia e Herzegovina', 'Europa', FALSE),
    ('BW', 'Botsuana', 'África', FALSE),
    ('BN', 'Brunei', 'Ásia', FALSE),
    ('BG', 'Bulgária', 'Europa', FALSE),
    ('BF', 'Burkina Faso', 'África', FALSE),
    ('BI', 'Burundi', 'África', FALSE),
    ('CV', 'Cabo Verde', 'África', FALSE),
    ('KH', 'Camboja', 'Ásia', TRUE),
    ('CM', 'Camarões', 'África', FALSE),
    ('CA', 'Canadá', 'América do Norte', FALSE),
    ('CF', 'República Centro-Africana', 'África', FALSE),
    ('TD', 'Chade', 'África', TRUE),
    ('CL', 'Chile', 'América do Sul', FALSE),
    ('CN', 'China', 'Ásia', FALSE),
    ('CO', 'Colômbia', 'América do Sul', FALSE),
    ('KM', 'Comores', 'África', TRUE),
    ('CG', 'Congo', 'África', TRUE),
    ('CD', 'República Democrática do Congo', 'África', TRUE),
    ('CR', 'Costa Rica', 'América do Norte', FALSE),
    ('CI', 'Costa do Marfim', 'África', TRUE),
    ('HR', 'Croácia', 'Europa', FALSE),
    ('CU', 'Cuba', 'América do Norte', TRUE),
    ('CY', 'Chipre', 'Ásia', FALSE),
    ('CZ', 'Tchéquia', 'Europa', FALSE),
    ('DK', 'Dinamarca', 'Europa', FALSE),
    ('DJ', 'Djibuti', 'África', TRUE),
    ('DM', 'Dominica', 'América do Norte', FALSE),
    ('DO', 'República Dominicana', 'América do Norte', FALSE),
    ('EC', 'Equador', 'América do Sul', FALSE),
    ('EG', 'Egito', 'África', TRUE),
    ('SV', 'El Salvador', 'América do Norte', FALSE),
    ('GQ', 'Guiné Equatorial', 'África', TRUE),
    ('ER', 'Eritreia', 'África', TRUE),
    ('EE', 'Estônia', 'Europa', FALSE),
    ('SZ', 'Essuatíni', 'África', FALSE),
    ('ET', 'Etiópia', 'África', FALSE),
    ('FJ', 'Fiji', 'Oceania', FALSE),
    ('FI', 'Finlândia', 'Europa', FALSE),
    ('FR', 'França', 'Europa', FALSE),
    ('GA', 'Gabão', 'África', TRUE),
    ('GM', 'Gâmbia', 'África', TRUE),
    ('GE', 'Geórgia', 'Ásia', FALSE),
    ('DE', 'Alemanha', 'Europa', FALSE),
    ('GH', 'Gana', 'África', TRUE),
    ('GR', 'Grécia', 'Europa', FALSE),
    ('GD', 'Granada', 'América do Norte', FALSE),
    ('GT', 'Guatemala', 'América do Norte', FALSE),
    ('GN', 'Guiné', 'África', TRUE),
    ('GW', 'Guiné-Bissau', 'África', TRUE),
    ('GY', 'Guiana', 'América do Sul', FALSE),
    ('HT', 'Haiti', 'América do Norte', TRUE),
    ('HN', 'Honduras', 'América do Norte', FALSE),
    ('HU', 'Hungria', 'Europa', FALSE),
    ('IS', 'Islândia', 'Europa', FALSE),
    ('IN', 'Índia', 'Ásia', TRUE),
    ('ID', 'Indonésia', 'Ásia', FALSE),
    ('IR', 'Irã', 'Ásia', TRUE),
    ('IQ', 'Iraque', 'Ásia', TRUE),
    ('IE', 'Irlanda', 'Europa', FALSE),
    ('IL', 'Israel', 'Ásia', FALSE),
    ('IT', 'Itália', 'Europa', FALSE),
    ('JM', 'Jamaica', 'América do Norte', FALSE),
    ('JP', 'Japão', 'Ásia', FALSE),
    ('JO', 'Jordânia', 'Ásia', TRUE),
    ('KZ', 'Cazaquistão', 'Ásia', TRUE),
    ('KE', 'Quênia', 'África', TRUE),
    ('KI', 'Kiribati', 'Oceania', FALSE),
    ('KW', 'Kuwait', 'Ásia', FALSE),
    ('KG', 'Quirguistão', 'Ásia', TRUE),
    ('LA', 'Laos', 'Ásia', TRUE),
    ('LV', 'Letônia', 'Europa', FALSE),
    ('LB', 'Líbano', 'Ásia', FALSE),
    ('LS', 'Lesoto', 'África', TRUE),
    ('LR', 'Libéria', 'África', TRUE),
    ('LY', 'Líbia', 'África', TRUE),
    ('LI', 'Liechtenstein', 'Europa', FALSE),
    ('LT', 'Lituânia', 'Europa', FALSE),
    ('LU', 'Luxemburgo', 'Europa', FALSE),
    ('MG', 'Madagascar', 'África', TRUE),
    ('MW', 'Malawi', 'África', TRUE),
    ('MY', 'Malásia', 'Ásia', FALSE),
    ('MV', 'Maldivas', 'Ásia', TRUE),
    ('ML', 'Mali', 'África', TRUE),
    ('MT', 'Malta', 'Europa', FALSE),
    ('MH', 'Ilhas Marshall', 'Oceania', FALSE),
    ('MR', 'Mauritânia', 'África', TRUE),
    ('MU', 'Maurício', 'África', FALSE),
    ('MX', 'México', 'América do Norte', FALSE),
    ('FM', 'Micronésia', 'Oceania', FALSE),
    ('MD', 'Moldávia', 'Europa', FALSE),
    ('MC', 'Mônaco', 'Europa', FALSE),
    ('MN', 'Mongólia', 'Ásia', FALSE),
    ('ME', 'Montenegro', 'Europa', FALSE),
    ('MA', 'Marrocos', 'África', TRUE),
    ('MZ', 'Moçambique', 'África', TRUE),
    ('MM', 'Myanmar', 'Ásia', FALSE),
    ('NA', 'Namíbia', 'África', FALSE),
    ('NR', 'Nauru', 'Oceania', FALSE),
    ('NP', 'Nepal', 'Ásia', TRUE),
    ('NL', 'Países Baixos', 'Europa', FALSE),
    ('NZ', 'Nova Zelândia', 'Oceania', FALSE),
    ('NI', 'Nicarágua', 'América do Norte', FALSE),
    ('NE', 'Níger', 'África', TRUE),
    ('NG', 'Nigéria', 'África', TRUE),
    ('KP', 'Coreia do Norte', 'Ásia', TRUE),
    ('MK', 'Macedônia do Norte', 'Europa', FALSE),
    ('NO', 'Noruega', 'Europa', FALSE),
    ('OM', 'Omã', 'Ásia', TRUE),
    ('PK', 'Paquistão', 'Ásia', TRUE),
    ('PW', 'Palau', 'Oceania', FALSE),
    ('PA', 'Panamá', 'América do Norte', FALSE),
    ('PG', 'Papua-Nova Guiné', 'Oceania', FALSE),
    ('PY', 'Paraguai', 'América do Sul', FALSE),
    ('PE', 'Peru', 'América do Sul', FALSE),
    ('PH', 'Filipinas', 'Ásia', FALSE),
    ('PL', 'Polônia', 'Europa', FALSE),
    ('PT', 'Portugal', 'Europa', FALSE),
    ('QA', 'Catar', 'Ásia', FALSE),
    ('RO', 'Romênia', 'Europa', FALSE),
    ('RU', 'Rússia', 'Europa', FALSE),
    ('RW', 'Ruanda', 'África', TRUE),
    ('KN', 'São Cristóvão e Névis', 'América do Norte', FALSE),
    ('LC', 'Santa Lúcia', 'América do Norte', FALSE),
    ('VC', 'São Vicente e Granadinas', 'América do Norte', FALSE),
    ('WS', 'Samoa', 'Oceania', FALSE),
    ('SM', 'San Marino', 'Europa', FALSE),
    ('ST', 'São Tomé e Príncipe', 'África', FALSE),
    ('SA', 'Arábia Saudita', 'Ásia', TRUE),
    ('SN', 'Senegal', 'África', TRUE),
    ('RS', 'Sérvia', 'Europa', FALSE),
    ('SC', 'Seychelles', 'África', FALSE),
    ('SL', 'Serra Leoa', 'África', TRUE),
    ('SG', 'Singapura', 'Ásia', FALSE),
    ('SK', 'Eslováquia', 'Europa', FALSE),
    ('SI', 'Eslovênia', 'Europa', FALSE),
    ('SB', 'Ilhas Salomão', 'Oceania', FALSE),
    ('SO', 'Somália', 'África', TRUE),
    ('ZA', 'África do Sul', 'África', FALSE),
    ('KR', 'Coreia do Sul', 'Ásia', FALSE),
    ('SS', 'Sudão do Sul', 'África', TRUE),
    ('ES', 'Espanha', 'Europa', FALSE),
    ('LK', 'Sri Lanka', 'Ásia', TRUE),
    ('SD', 'Sudão', 'África', TRUE),
    ('SR', 'Suriname', 'América do Sul', FALSE),
    ('SE', 'Suécia', 'Europa', FALSE),
    ('CH', 'Suíça', 'Europa', FALSE),
    ('SY', 'Síria', 'Ásia', FALSE),
    ('TJ', 'Tajiquistão', 'Ásia', FALSE),
    ('TZ', 'Tanzânia', 'África', TRUE),
    ('TH', 'Tailândia', 'Ásia', FALSE),
    ('TL', 'Timor-Leste', 'Ásia', FALSE),
    ('TG', 'Togo', 'África', TRUE),
    ('TO', 'Tonga', 'Oceania', FALSE),
    ('TT', 'Trinidad e Tobago', 'América do Norte', FALSE),
    ('TN', 'Tunísia', 'África', FALSE),
    ('TR', 'Turquia', 'Ásia', FALSE),
    ('TM', 'Turcomenistão', 'Ásia', FALSE),
    ('TV', 'Tuvalu', 'Oceania', FALSE),
    ('UG', 'Uganda', 'África', TRUE),
    ('UA', 'Ucrânia', 'Europa', FALSE),
    ('AE', 'Emirados Árabes Unidos', 'Ásia', FALSE),
    ('GB', 'Reino Unido', 'Europa', FALSE),
    ('US', 'Estados Unidos', 'América do Norte', FALSE),
    ('UY', 'Uruguai', 'América do Sul', FALSE),
    ('UZ', 'Uzbequistão', 'Ásia', TRUE),
    ('VU', 'Vanuatu', 'Oceania', TRUE),
    ('VE', 'Venezuela', 'América do Sul', FALSE),
    ('VN', 'Vietnã', 'Ásia', TRUE),
    ('YE', 'Iêmen', 'Ásia', TRUE),
    ('ZM', 'Zâmbia', 'África', TRUE),
    ('ZW', 'Zimbábue', 'África', TRUE);

INSERT INTO regiao (nome)
VALUES
('América do Sul'),
('América Central'),
('Caribe'),
('América do Norte'),
('Europa Ocidental'),
('Europa Oriental'),
('Oriente Médio'),
('África Subsaariana'),
('Norte da África'),
('Ásia Central'),
('Leste Asiático'),
('Sul Asiático'),
('Sudeste Asiático'),
('Oceania');


INSERT INTO proprietario (nome, cpf_cnpj, telefone, email)
VALUES 
	('José Alfredo dos Santos', '12345678900', '(11) 9898-0202', 'josealfredosantos@gmail.com'),
	('Maria do Carmo Almeida', '45678000100', '(21) 3204-1236', 'mariadocarmo@gmail.com'),
	('Carlota do Desterro Albuquerque', '99811222333', '(11) 98888-2211', 'carlota.albuquerque@gmail.com'),
	('Grupo Esperança Humanitária', '44566789000155', '(21) 3344-8822', 'contato@esperancahumanitaria.org'),
	('Alessandra Paula Rodrigues', '88211999000', '(31) 97771-5544', 'alessandra.rodrigues@hotmail.com'),
	('Instituto Novo Recomeço', '11788999000102', '(85) 3221-7700', 'acolhimento@novorecomeco.org'),
	('Mohammed Al-Hassan', '77711222991', '(41) 99881-1000', 'm.alhassan@gmail.com');

INSERT INTO alojamento (id_proprietario, tamanho_m2)
VALUES 
(1, 100),
(1, 50),
(1, 36),
(2, 74.8),
(3, 82.5),
(4, 120),
(5, 65),
(6, 210),
(7, 58),
(4, 360),
(6, 120),
(7, 85),
(5, 50);


INSERT INTO endereco (id_alojamento, logradouro, cidade, estado, cep)
VALUES 
	(1, 'Rua das Macieiras, 14 apt 301', 'São Paulo', 'SP', '01001000'),
	(2, 'Rua da Consolação, 120', 'Guaianases', 'SP', '01250001'),
	(3, 'Rua dos Orvalhos, 200', 'Governador Valadares', 'MG', '34500102'),
	(4, 'Avenida das Araucárias, 191', 'Fortaleza', 'CE', '60101000'),
	(5, 'Rua dos Beija-Flores Serelepes, 221', 'Campina Grande', 'PB', '58010900'),
	(6, 'Rua da Imbiribeira, 970', 'Feira de Santana', 'BA', '40300000'),
	(7, 'Travessa Padre Anchieta, 1500', 'Recife', 'PE', '55200000'),
	(8, 'Rua da Espada, 700', 'Aparecida de Goiania', 'GO', '74020020'),
	(9, 'Rua Professora Rita de Cassia, 100', 'Belo Horizonte', 'MG', '30110000'),
	(10, 'Rua dos Lírios, 567', 'Rio de Janeiro', 'RJ', '06730000'),
	(11, 'Rua do Capim Vermelho, 888', 'Boa Vista', 'RR', '69300000'),
	(12, 'Rua dos Pregos, 6780', 'Manaus', 'AM', '27949000'),
	(13, 'Rua Madre Teresa, 500', 'Ponta Porã', 'MS', '79900000');


INSERT INTO familia (nome_referencia) VALUES 
	('Ahmed'),
	('Chen'),
	('Nazarov'),
	('Mendez'),
	('Singh'),
	('Petersen'),
	('Schuhmacher'),
	('Al-Qamar'),
	('Soares Carneiro'),
	('Andrianiombonana'),
	('Abdullah'),
	('Rodriguez'),
	('Mendoza'),
	('Ramirez'),
	('Suarez'),
	('Castillo'),
	('Al-Chamms');

INSERT INTO imigrante (id_familia, nome, id_pais, nr_passaporte, sexo, data_nascimento, tipo_migrante)
VALUES 
	(1, 'Muhammad Ahmed', 'AF', 'AB123456', 'M', '1990-01-01', 'refugiado'),
	(1, 'Iman Ahmed', 'AF', 'AB789000', 'F', '1992-09-03', 'refugiado'),
	(1, 'Mina Ahmed', 'AF', NULL, 'M', '1990-01-01', 'refugiado'),
	(2, 'Ling Chen', 'CN', 'CHN192094', 'F', '1989-02-20', 'imigrante'),
	(2, 'Ping Chen', 'CN', 'CHN124894', 'F', '1988-12-30', 'imigrante'),
	(2, 'Qiao Chen', 'CN', 'CHN299074', 'M', '2010-04-19', 'imigrante'),
	(2, 'Yang Chen', 'CN', 'CHN333467', 'M', '2000-01-02', 'imigrante'),
	(2, 'Huang Chen', 'CN', 'CHN320329', 'F', '1996-07-24', 'imigrante'),
	(3, 'Sergey Nazarov', 'RU', 'RUS646019', 'M', '1994-05-06', 'imigrante'),
	(3, 'Olga Nazarov', 'RU', 'RUS999434', 'F', '1997-11-15', 'imigrante'),
	(3, 'Boris Nazarov', 'RU', 'RUS131312', 'M', '2020-09-09', 'imigrante'),
	(3, 'Darina Nazarov', 'RU', 'RUS778919', 'M', '1956-10-04', 'imigrante'),
	(4, 'Miguél Mendez', 'VE', 'M', '1985-01-26', 'refugiado'),
	(4, 'María Guadalupe Alvarez Mendez', 'VE','F', '1990-08-16', 'refugiado'),
	(4, 'Tiffany Mendez', 'VE', 'F', '2009-11-18', 'refugiado'),
	(4, 'Roberto Mendez', 'VE', 'F', '2011-05-06', 'refugiado'),
	(5, 'Priya Rajee Singh', 'IN', 'IND182392', 'F', '1999-03-12', 'imigrante'),
	(5, 'Devi Singh', 'IN', 'IND657293', 'F', '2022-04-22', 'imigrante'),
	(5, 'Raj Singh', 'IN', 'IND473576', 'M', '2008-09-24', 'imigrante'),
	(6, 'Oskar Petersen', 'SE', 'SWE822967', 'M', '1995-11-23', 'imigrante'),
	(7, 'Hans Schuhmacher', 'DE', 'DEU223474', 'M', '2002-04-08', 'imigrante'),
	(7, 'Oxana Schuhmacher Papadopoulos', 'GR', 'GRE0192231', 'F', '2000-10-20', 'imigrante'),
	(8, 'Farid Al-Qamar', 'SY', 'M', '1972-12-24', 'refugiado'),
	(8 'Amina Al-Qamar', 'SY', 'F', '1988-06-26', 'refugiado'),
	(9, 'Maria de la Purificación Soares Carneiro', 'GQ', 'GEQ001239', 'F', '1988-11-03', 'imigrante'),
	(9, 'Marcos Cassermiro Soares Carneiro', 'GQ', 'GEQ877524', 'M', '1986-08-29', 'imigrante'),
	(10, 'Toky Andrianiombonana', 'MG', 'MDG039334', 'M', '1989-07-10', 'imigrante'),
	(11, 'Ahmad bin Abdullah', 'MY', 'MAL393092', 'M', '1977-03-17', 'imigrante'),
	(11, 'Aisyah binti Muhammad Ali', 'MY', 'MAL643453', 'F', '1984-01-11', 'imigrante'),
	(11, 'Siti binti Ahmad', 'MY', 'MAL123459', 'F', '2007-07-12', 'imigrante'),
	(12, 'José Antonio Rodríguez', 'VE', NULL, 'M', '1982-04-11', 'refugiado'),
	(12, 'María Fernanda Rodríguez', 'VE', NULL, 'F', '1986-09-27', 'refugiado'),
	(12, 'Luis Rodríguez', 'VE', NULL, 'M', '2010-01-19', 'refugiado'),
	(12, 'Camila Rodríguez', 'VE', NULL, 'F', '2014-06-03', 'refugiado'),
	(13, 'Carlos Eduardo Mendoza', 'VE', NULL, 'M', '1978-03-05', 'refugiado'),
	(13, 'Patricia Mendoza', 'VE', NULL, 'F', '1981-07-30', 'refugiado'),
	(13, 'Daniel Mendoza', 'VE', NULL, 'M', '2007-11-21', 'refugiado'),
	(14, 'Miguel Ángel Ramírez', 'VE', NULL, 'M', '1990-12-18', 'refugiado'),
	(14, 'Andrea Ramírez', 'VE', NULL, 'F', '1994-05-10', 'refugiado'),
	(14, 'Sofía Ramírez', 'VE', NULL, 'F', '2018-02-14', 'refugiado'),
	(15, 'Roberto Suárez', 'VE', NULL, 'M', '1985-08-01', 'refugiado'),
	(15, 'Lucía Suárez', 'VE', NULL, 'F', '1989-03-29', 'refugiado'),
	(15, 'Mateo Suárez', 'VE', NULL, 'M', '2012-09-22', 'refugiado'),
	(15, 'Valentina Suárez', 'VE', NULL, 'F', '2016-12-04', 'refugiado'),
	(16, 'Fernando Castillo', 'VE', NULL, 'M', '1975-01-15', 'refugiado'),
	(16, 'Gabriela Castillo', 'VE', NULL, 'F', '1980-10-09', 'refugiado'),
	(16, 'Isabella Castillo', 'VE', NULL, 'F', '2009-04-07', 'refugiado'),
	(16, 'Tomás Castillo', 'VE', NULL, 'M', '2015-07-11', 'refugiado'),
	(17, 'Yousseff Ali Al-Chamms', 'TN', NULL, 'M', '1992-12-10', 'refugiado'),
	(17, 'Iman Al-Chamms', 'EG', 'EGY193332', 'F', '1998-08-04', 'refugiado');


INSERT INTO familia_alojamento (id_familia, id_alojamento, data_entrada) VALUES 
	(1, 1, '2020-02-07'), 
	(2, 1, '2020-02-15'),
	(3, 2, '2020-03-04'),
	(4, 3, '2020-03-19'), 
	(5, 1, '2021-01-11'),
	(6, 4, '2021-02-28'), 
	(10, 1, '2021-04-08'),
	(12, 14, '2021-06-29'),
	(13, 14, '2021-12-28'),
	(14, 14, '2022-01-02'), 
	(15, 14, '2023-07-20'), 
	(16, 14, '2023-09-28'), 
	(17, 15, '2024-04-17');

INSERT INTO familia_alojamento (id_familia, id_alojamento, data_entrada, data_saida, status) VALUES 
	(15, 10, '2022-02-27', '2023-05-31', 'inativo'),
	(10, 4, '2020-10-18', '2021-08-02', 'inativo');
	

INSERT INTO estado VALUES 
('AC', 'Acre'),
('AL', 'Alagoas'),
('AP', 'Amapá'),
('AM', 'Amazonas'),
('BA', 'Bahia'),
('CE', 'Ceará'),
('DF', 'Distrito Federal'),
('ES', 'Espírito Santo'),
('GO', 'Goiás'),
('MA', 'Maranhão'),
('MT', 'Mato Grosso'),
('MS', 'Mato Grosso do Sul'),
('MG', 'Minas Gerais'),
('PA', 'Pará'),
('PB', 'Paraíba'),
('PR', 'Paraná'),
('PE', 'Pernambuco'),
('PI', 'Piauí'),
('RJ', 'Rio de Janeiro'),
('RN', 'Rio Grande do Norte'),
('RS', 'Rio Grande do Sul'),
('RO', 'Rondônia'),
('RR', 'Roraima'),
('SC', 'Santa Catarina'),
('SP', 'São Paulo'),
('SE', 'Sergipe'),
('TO', 'Tocantins');

